from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple, Union

SqlResult = Union[List[Dict[str, Any]], int, None]

ERROR_CONNECT_FAILED: str
ERROR_TIMEOUT: str
ERROR_PROTOCOL: str
ERROR_UNSUPPORTED: str
ERROR_INVALID_TARGET: str
ERROR_CLOSED: str
CLIENT_ERROR_CODES: Tuple[str, ...]
DEFAULT_TIMEOUT: float
DEFAULT_IDLE_RECONNECT_SECONDS: float

TARGET_REMOTE: str
TARGET_MEMORY: str
TARGET_PATH: str
EMBEDDED_CONNECT_OPTIONS: Tuple[str, ...]


def resolve_connect_target(
    target: str, options: Mapping[str, Any]
) -> Tuple[str, str]: ...


class RemoteTransaction:
    @property
    def session_id(self) -> str: ...
    @property
    def expires_at(self) -> Optional[str]: ...
    @property
    def status(self) -> Dict[str, str]: ...
    def execute_sql(
        self,
        sql: str,
        params: Optional[Sequence[Any]] = None,
        *,
        timeout: Optional[float] = None,
    ) -> SqlResult: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> "RemoteTransaction": ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> bool: ...
    def execute_sql_stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def query_stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def put(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...
    def upsert_vector(self, *args: Any, **kwargs: Any) -> Any: ...
    def search_similar(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_vector(self, *args: Any, **kwargs: Any) -> Any: ...
    def upsert_to_hnsw(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_from_hnsw(self, *args: Any, **kwargs: Any) -> Any: ...


class RemoteDatabase:
    def __init__(
        self,
        url: str,
        *,
        api_key: Optional[str] = None,
        timeout: float = ...,
        sql_path: Optional[str] = None,
        api_prefix: Optional[str] = None,
        headers: Optional[Mapping[str, str]] = None,
        ssl_context: Any = None,
        insecure: bool = False,
        retries: int = 0,
        keep_alive: bool = True,
        idle_reconnect_seconds: Optional[float] = ...,
    ) -> None: ...
    @classmethod
    def connect(cls, url: str, **options: Any) -> "RemoteDatabase": ...
    @property
    def url(self) -> str: ...
    @property
    def sql_path(self) -> str: ...
    @property
    def last_routing_diagnostics(self) -> List[Any]: ...
    @property
    def thread_mode(self) -> Any: ...
    def execute_sql(
        self,
        sql: str,
        params: Optional[Sequence[Any]] = None,
        *,
        timeout: Optional[float] = None,
    ) -> SqlResult: ...
    def begin(self, mode: Optional[Any] = None) -> RemoteTransaction: ...
    def cluster_status(self) -> Dict[str, Any]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "RemoteDatabase": ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> bool: ...
    def execute_sql_stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def query_stream(self, *args: Any, **kwargs: Any) -> Any: ...
    def execute_shared(self, *args: Any, **kwargs: Any) -> Any: ...
    def prepare(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy_from_csv(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy_to_csv(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_sequences(self, *args: Any, **kwargs: Any) -> Any: ...
    def flush(self, *args: Any, **kwargs: Any) -> Any: ...
    def memory_usage(self, *args: Any, **kwargs: Any) -> Any: ...
    def routing_diagnostics(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_hnsw_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def search_hnsw(self, *args: Any, **kwargs: Any) -> Any: ...
    def drop_hnsw_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_hnsw_stats(self, *args: Any, **kwargs: Any) -> Any: ...
    @classmethod
    def open(cls, *args: Any, **kwargs: Any) -> "RemoteDatabase": ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> "RemoteDatabase": ...
    @classmethod
    def open_in_memory(cls, *args: Any, **kwargs: Any) -> "RemoteDatabase": ...
    @classmethod
    def open_with_config(cls, *args: Any, **kwargs: Any) -> "RemoteDatabase": ...
